In [1]:
import numpy as np
import random

In [67]:
count = 0
class Game():
    def __init__(self):
        self.pig = np.zeros(55)
        self.pig[27] = 1
        self.stone = np.zeros(55)
        self.grass = np.zeros(55)
        self.moves = 3
        self.gameBoard = None
        self.edgespaces = [0,1,2,3,4,5,9,10,14,15,19,20,24,25,29,30,34,35,39,40,44,45,49,50,51,52,53,54,55]
        self.chosenMoves = []
        self.level = 0
    def possibleMoves(self):
        arr = []
        for x in range(55):
            if self.gameBoard[x] == 0:
                arr.append(x)
        return arr
    def lost(self):
        for x in range(55):
          if self.gameBoard[x] == 2:
            old = x
            break
        if old in self.edgespaces:
            return True
        else:
            return False
    def won(self):
        x,__ = self.pigNextMoveFF()
        if x == None:
            return True
        else:
            return False
    def generateGameBoard(self, difficulty):  # 1(easy) to 5(hard)
        self.randomGameBoard(difficulty)
        if difficulty == 1:
            self.gameBoard = np.array([0.,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0])
        if difficulty == 2:
            self.gameBoard = np.array([0.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,2,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
        if difficulty == 3:
            self.gameBoard = np.array([0.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,2,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
        if difficulty == 4:
            self.gameBoard = np.array([0.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,2,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
        if difficulty == 5:
            self.gameBoard = np.array([0.,1,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,1,2,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
        if difficulty == 6:
            self.gameBoard = np.array([1., 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
                                      0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])
        if difficulty == 7:
            self.gameBoard = np.array([0., 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
                                       0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])
        if difficulty == 8:
            self.gameBoard = np.array([1., 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
                                       0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
        if difficulty == 9:
            self.gameBoard = np.array([0., 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
                                       0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
        if difficulty == 10:
            self.gameBoard = np.array([0., 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
                                       0, 1, 0, 0, 2, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
        #self.separateGameBoard()

    def randomGameBoard(self,difficulty):
        self.gameBoard = np.zeros(55)
        for x in range(55):
            if random.random() > (.60 + (.01 * difficulty)):
                self.gameBoard[x] = 1
        self.gameBoard[27] = 2
        #nextMov, pigLoc = self.pigNextMoveFF()
        #if nextMov == None:
            #self.randomGameBoard(difficulty)

    def printArr(self, arr):
        for x in range(11):
            if ((x + 1) % 2) == 0:
                y = "  "
            else:
                y = ""
            print(y, arr[(x*5):(x*5)+5])

    def pigNextMoveFF(self):
        newLoc = None
        fillPath = np.zeros(55)
        pigLoc = None
        for x in range(55):
            if self.gameBoard[x] == 2:
                pigLoc = x
                break
        if pigLoc == None:
            return None,None
        if pigLoc in self.edgespaces:
            return (pigLoc , pigLoc)
        # if self.pigLoc < 5 or self.pigLoc > 49 or self.pigLoc % 5 == 0 or (self.pigLoc - 4) % 5 == 0: ## this includes all the edges of the gameBoard array
            # return 69 # returns none if pig is on edge
        #self.printArr(self.gameBoard)
        fillPath[pigLoc] = 1
        for iteration in range(12):  # flood fill
            for loc in range(55):
                if fillPath[loc] == iteration + 1:
                    if int(str(loc)[len(str(loc)) - 1]) < 6:
                        x = -1
                    else:
                        x = 0
                    if (loc - 1) < 55 and (loc - 1) >= 0 and self.gameBoard[loc - 1] == 0 and fillPath[loc - 1] == 0:
                        fillPath[loc - 1] = iteration + 2
                    if (loc + 1) < 55 and (loc + 1) >= 0 and self.gameBoard[loc + 1] == 0 and fillPath[loc + 1] == 0:
                        fillPath[loc + 1] = iteration + 2
                    if (loc - 5 + x) < 55 and (loc - 5 + x) >= 0 and self.gameBoard[loc - 5 + x] == 0 and fillPath[loc - 5 + x] == 0:
                        fillPath[loc - 5 + x] = iteration + 2
                    if (loc - 4 + x) < 55 and (loc - 4 + x) >= 0 and self.gameBoard[loc - 4 + x] == 0 and fillPath[loc - 4 + x] == 0:
                        fillPath[loc - 4 + x] = iteration + 2
                    if (loc + 5 + x) < 55 and (loc + 5 + x) >= 0 and self.gameBoard[loc + 5 + x] == 0 and fillPath[loc + 5 + x] == 0:
                        fillPath[loc + 5 + x] = iteration + 2
                    if (loc + 6 + x) < 55 and (loc + 6 + x) >= 0 and self.gameBoard[loc + 6 + x] == 0 and fillPath[loc + 6 + x] == 0:
                        fillPath[loc + 6 + x] = iteration + 2
                    
                    
            for loc in range(55):
                if loc < 5 or loc > 49 or loc % 5 == 0 or (loc - 4) % 5 == 0:
                    if fillPath[loc] > 0:  # next move found

                        loc1 = loc
                        count = 0
                        while fillPath[loc1] != 2:
                            count += 1
                            if count > 20:
                                pass
                                #print()
                                #self.printArr(self.gameBoard)
                                #print()
                                #print(
                                #    "value of fillPath[loc1]: ", fillPath[loc1], " value: ", loc1)
                                #game.printArr(fillPath)
                            if int(str(loc1)[len(str(loc1)) - 1]) < 5:
                                x = -1
                            else:
                                x = 0
                                
                            if (loc1 - 1) < 55 and (loc1 - 1) >= 0 and fillPath[loc1 - 1] < fillPath[loc1] and fillPath[loc1 - 1] > 0 and loc % 5 != 0:
                                loc1 = loc1 - 1
                                continue
                            if (loc1 + 1) < 55 and (loc1 + 1) >= 0 and fillPath[loc1 + 1] < fillPath[loc1] and fillPath[loc1 + 1] > 0 and (loc - 4) % 5 != 0:
                                loc1 = loc1 + 1
                                continue
                            if (loc1 - 5 + x) < 55 and (loc1 - 5 + x) >= 0 and fillPath[loc1 - 5 + x] < fillPath[loc1] and fillPath[loc1 - 5 + x] > 0:
                                loc1 = loc1 - 5 + x
                                continue
                            if (loc1 - 4 + x) < 55 and (loc1 - 4 + x) >= 0 and fillPath[loc1 - 4 + x] < fillPath[loc1] and fillPath[loc1 - 4 + x] > 0:
                                loc1 = loc1 - 4 + x
                                continue
                            
                            if (loc1 + 5 + x) < 55 and (loc1 + 5 + x) >= 0 and fillPath[loc1 + 5 + x] < fillPath[loc1] and fillPath[loc1 + 5 + x] > 0:
                                loc1 = loc1 + 5 + x
                                continue
                            if (loc1 + 6 + x) < 55 and (loc1 + 6 + x) >= 0 and fillPath[loc1 + 6 + x] < fillPath[loc1] and fillPath[loc1 + 6 + x] > 0:
                                loc1 = loc1 + 6 + x
                                continue
                            
                            
                        newLoc = loc1
                        # 0 - 54 related to the gameBoard array index # the current location of the pig
                        return newLoc, pigLoc
                # else:
                    # if loc == 55: # last point in array checked so if even the last index has a value of zero then there are no paths and player wins

                        # return newLoc # no next move means player wins # still return pigLoc for continuity of return within the function
        newLoc = None
        return newLoc, pigLoc

    def newBoard(self,pos):
        global count
        count+=1
        newGame = Game()
        newGame.chosenMoves = self.chosenMoves.copy()
        newGame.gameBoard = self.gameBoard.copy()
        if self.moves > 1:
            newGame.moves = self.moves - 1
            newGame.gameBoard[pos] = 1
            newGame.chosenMoves.append(pos)
        else:
            newGame.gameBoard[pos] = 1
            newGame.chosenMoves.append(pos)
            NewPig , OldPig = newGame.pigNextMoveFF()
            if NewPig ==None:
                print("solution is ", newGame.chosenMoves)
                return newGame
            #print(NewPig,"PigisHere")
            newGame.gameBoard[OldPig] = 0
            newGame.gameBoard[NewPig] = 2
            #print("placing pig at " ,NewPig)
            newGame.moves = 1
        return newGame
    def sortedlist(self):
        arr = self.possibleMoves()
        organarr = []
        start = 27
        if start in arr:
            organarr.append(start)
        for x in range(1,28):
            if start - x in arr:
                organarr.append(start - x)
            if start + x in arr:
                organarr.append(start + x)
        return organarr
    def solve(self,depth):
        #see if current Version is solved
        #print(self.level)
        num = 0
        if self.won() == True:
            print("Won")
            return self.chosenMoves

        for x in self.sortedlist():
            if self.level >= depth:
                break
            #print("trying possible ",x)
            new = self.newBoard(x)
            #new = self.newBoard(26)
            #new = new.newBoard(28)
            #new = new.newBoard(22)
            #return new.chosenMoves
            #print()
            #new.printArr(new.gameBoard)
            #print()
            
            if new.won():
                #print(new.chosenMoves)
                return new.chosenMoves
            new.level = self.level + 1
            if new.level ==1:
                #print(num, count)
                num+=1
                #print(new.level, " recursion Level")
            if new.lost() == True:
                #print(x ,"didnt Work")
                continue
            a = new.solve(depth)
            if new.won():
                print("won")
                return new.solve(depth)
            if a!=None:
                return a
    def solvetoDepth(self):
        for x in range(12):
            a = self.solve(x)
            if a != None:
                return a
            

In [68]:
game = Game()
game.generateGameBoard(1)
game.printArr(game.gameBoard)

 [0. 0. 0. 0. 1.]
   [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
   [0. 0. 2. 1. 0.]
 [0. 0. 0. 0. 0.]
   [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
   [1. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]


In [69]:
print(game.pigNextMoveFF())

(23, 27)


In [70]:
print(game.solve(12), 'solve')

solution is  [26, 25, 18, 24, 11, 15, 20, 12, 27]
[26, 25, 18, 24, 11, 15, 20, 12, 27] solve


In [64]:
count

2587902

In [ ]:
game.printArr(game.gameBoard)

In [ ]:
new = game.newBoard(26)
new = new.newBoard(28)
new = new.newBoard(22)

In [ ]:
new.printArr(new.gameBoard)

In [ ]:
new.won()